pkg/build.sh
pkg/opte.template.p5m
xde/xde.conf

Without `/kernel/drv/xde.conf` the `xde` driver will fail to attach. This commit adds `xde.conf` to the p5p package for `xde`.

packaging: add xde.conf to p5p package

---

opte/src/engine/flow_table.rs
opte/src/engine/int_test.rs
opte/src/engine/ioctl.rs
opte/src/engine/layer.rs
opte/src/engine/nat.rs
opte/src/engine/port.rs
opte/src/engine/rule.rs
opte/src/oxide_vpc/engine/arp.rs
opte/src/oxide_vpc/engine/dhcp4.rs
opte/src/oxide_vpc/engine/dyn_nat4.rs
opte/src/oxide_vpc/engine/firewall.rs
opte/src/oxide_vpc/engine/icmp.rs
opte/src/oxide_vpc/engine/overlay.rs
opte/src/oxide_vpc/engine/router.rs
opteadm/src/main.rs
xde/src/xde.rs

Other stuff that came along for the ride:
* UFT, LFT, and TCP table limits are now expressed via NonZeroU32.
* Table limits are now a required argument.
* Changed LFT expiration to be purely based on outbound for the
moment. I don't really love this.
* Added Resource/ResourceMap traits and implemented the SNAT pool in
terms of them.
* Implemented resource release for SNAT.
* Ditched the `ActionDesc::fini()` idea and replaced it with `Drop`
impl.
* More extensive SNAT unit test, part of which verifies resource
acquisition and release.

PR: Do not panic on failed LFT pair allocation (#150)

---

dtrace/opte-port-process.d
opte/process-flow.md
opte/src/engine/int_test.rs
opte/src/engine/nat.rs
opte/src/oxide_vpc/api.rs
opte/src/oxide_vpc/engine/nat4.rs
opteadm/src/main.rs
xde/src/xde.rs

This modifies the hacked up NAT layer to always rewrite external
traffic to the local gateway on the "external" subnet. When the
destination is another IP on the subnet the gateway will just forward
it back onto the subnet. In the case of an off-subnet destination, the
gateway will forward it to the next hop. This allows bouth inbound and
outbound external traffic to work with the guest.
I also tried to get intra-guest (aka internal VPC traffic) to work
under the hack but it's fighting me and we want to land what's here
for the next demo.
I also modified the port process DTrace script to print more useful
info. And I added a start to a flowchart for processing flow.

ext-ip-hack: fwd all ext traffic to phys gateway

---

opte-api/check-api-version.awk
opte-api/check-api-version.sh
opte-api/src/ip.rs
opte-api/src/lib.rs
opte/Cargo.lock
opte/Cargo.toml
opte/src/engine/headers.rs
opte/src/engine/ip4.rs
opte/src/engine/ip6.rs
opte/src/engine/packet.rs

- Use smoltcp to parse IPv6 extension headers. This removes the
`Ipv6HdrRaw` and uses `smoltcp`'s "packet" types in its place.
- Store raw byte array (uninterpreted) corresponding to a packet's
extension headers in the `Ipv6Hdr` type. We only need the length, so
we know where the ULP starts, and the raw bytes, so we can re-emit
them in the processed packet.
- Adds tests verifying the handling of the four currently supported
extension headers

Add minimal support for IPv6 extension headers

---

opte-api/src/ip.rs
opte-api/src/lib.rs
opte-api/src/ndp.rs
opte/src/engine/icmpv6.rs
opte/src/engine/rule.rs
oxide-vpc/.gitignore
oxide-vpc/src/engine/icmpv6.rs
oxide-vpc/tests/integration_tests.rs

- Adds types for handling expected NDP messages, including Router and Neigbor Solicitations and Advertisements
- Reworks the ICMPv6 layer for `oxide-vpc` to include better Echo support, and adds new NDP handling.

Implements core NDP support

---

dtrace/opte-port-process.d
opte-api/src/dhcpv6.rs
opte-api/src/ip.rs
opte-api/src/lib.rs
opte-api/src/mac.rs
opte/src/engine/checksum.rs
opte/src/engine/dhcpv6/mod.rs
opte/src/engine/dhcpv6/options.rs
opte/src/engine/dhcpv6/protocol.rs
opte/src/engine/icmpv6.rs
opte/src/engine/ip4.rs
opte/src/engine/ip6.rs
opte/src/engine/mod.rs
opte/src/engine/packet.rs
opte/src/engine/rule.rs
oxide-vpc/.gitignore
oxide-vpc/src/api.rs
oxide-vpc/src/engine/dhcpv6.rs
oxide-vpc/src/engine/mod.rs
oxide-vpc/tests/integration_tests.rs
xde/src/xde.rs

- Adds core support for DHCPv6 types, including DUIDs, Options, and the various message types.
- Adds an OPTE API action for describing DHCPv6 emulation in OPTE, with the addresses to be leased, their lifetimes, and a few other options.
- Implements the DHCPv6 protocol inside the `Dhcpv6Action::gen_packet` method.
- Adds helper implementations of `AsRef` and `Deref` to MAC and IPv6 addresses, for referring to those as byte arrays without an additional copy.
- Adds ULP checksum computation to IPv6, and fixes small edge-case with computed checksums of zero.
- Adds a bunch of units for DHCPv6, mostly for serialization/deserialization, including test data from a packet capture.
- Adds integration tests verifying the core DHCPv6 protocol for leasing addresses, including Solicit -> Advertise -> …

Implements basic DHCPv6 support

---

opte/src/engine/checksum.rs

- Simplified the process of finalizing a rolling checksum and converting it into a header checksum.
- Removed `pub` access from `csum_sub()` as it's meant to be a private helper function.

Add some docs to checksum module

---

opte/src/engine/headers.rs
oxide-vpc/tests/common/icmp.rs
oxide-vpc/tests/common/mod.rs
oxide-vpc/tests/common/pcap.rs
oxide-vpc/tests/common/port_state.rs
oxide-vpc/tests/integration_tests.rs

Start moving some of the shared routines used in the integration tests to a common module. There's still more to move, but this is a good start.

Create common module for integration tests

---

oxide-vpc/src/engine/router.rs
oxide-vpc/tests/common/mod.rs
oxide-vpc/tests/common/port_state.rs
oxide-vpc/tests/integration_tests.rs

For most tests, we want the gust to have a route to other guests in its subnet. Move the router::add_entry() call to the common setup, and replace routes for the tests that need a different setup.
Added a `chk!` macro. It's like `assert!` but takes the additional PortAndVps argument so that the port state is printed on failure.
Added `router::replace()` API to allow replacing all routes for a guest in one, atomic operation.
Removed `check_no_flows()` which was obsoleted by the `VpcPortState` mechanism.

Bring router::add_entry into common setup

---

opte/src/engine/layer.rs
opte/src/engine/port.rs
oxide-vpc/src/engine/arp.rs
oxide-vpc/src/engine/dhcp.rs
oxide-vpc/src/engine/dhcpv6.rs
oxide-vpc/src/engine/firewall.rs
oxide-vpc/src/engine/icmp.rs
oxide-vpc/src/engine/icmpv6.rs
oxide-vpc/src/engine/nat.rs
oxide-vpc/src/engine/overlay.rs
oxide-vpc/src/engine/router.rs
oxide-vpc/tests/integration_tests.rs

Add the notion of a default action to a layer. In many cases, a layer is acting as either a filtering layer or a rewrite layer. A filtering layer provides an allow list of packets that may pass its boundary. A rewrite layer is meant to rewrite packets that match certain criteria, but otherwise let the packet pass untouched.
A default action specifies the action to take if a packet matches no rule in the layer. The default action can be that of allow or deny. Up to this point we've had an implicit default of allow, requiring filtering layers to maintain a rule denying any traffic that doesn't match the allow list. This mechanism for filtering was brittle because you have to remember to keep the deny rule in place. However, when allowing a control plane to replace all rules en masse it is …

Add notion of default action

---

opte/src/engine/headers.rs
opte/src/engine/packet.rs
opte/src/engine/port.rs
opte/src/engine/tcp.rs
opte/src/engine/udp.rs
oxide-vpc/tests/common/mod.rs
oxide-vpc/tests/common/port_state.rs
oxide-vpc/tests/firewall_tests.rs
oxide-vpc/tests/integration_tests.rs

Implement UFT pairing as described in VFP §6.4.1, with the exception of flow simulation, which isn't implemented yet. This pairing allows for better UFT invalidation logic and sets us up for truly handling asymmetric Unified Flow IDs (UFIDs) in the future.
I also wrote a pair of tests to make sure the UFT invalidation logic works. Though right now there exists a scenario where the outbound UFT entry will have a `pair` value of `None` even though an inbound UFT entry exists. This happens when the first packet for a flow arrives from the inbound direction, as it's only in the inbound direction that UFT entries can be paired, and we only perform this pairing when handling the first inbound packet. The reason pairing is only accomplished on inbound is because of the possibility of asymmetric …

Implement UFT pairing

---

opte/src/engine/ioctl.rs
opte/src/engine/port.rs
opte/src/engine/print.rs

Let there be light.
```
rpz@kalm:~/oxidecomputer/opte/xde$ pfexec opteadm dump-tcp-flows -p opte2
FLOW                                             STATE        HITS     SEGS IN  SEGS OUT BYTES IN   BYTES OUT 
TCP:172.30.0.5:22:10.0.0.10:52303                ESTABLISHED  214      124      91       12293      19055     
TCP:172.30.0.5:41334:34.69.170.43:80             TIME_WAIT    10       5        6        689        484       
rpz@kalm:~/oxidecomputer/opte/xde$ pfexec opteadm dump-tcp-flows -p opte2
FLOW                                             STATE        HITS     SEGS IN  SEGS OUT BYTES IN   BYTES OUT 
TCP:172.30.0.5:22:10.0.0.10:52303                ESTABLISHED  343      172      172      15981      109325    
TCP:172.30.0.5:41334:34.69.170.43:80             TIME_WAIT    10       5 …
```

Add per-tcp-flow stats

---

opte/src/engine/port.rs
oxide-vpc/tests/firewall_tests.rs
oxide-vpc/tests/integration_tests.rs
xde/src/xde.rs

The fact that `ActionMeta` was passed as a mutable reference to `Port::process()` was an artifact of some misunderstandings I had between the C and Rust parts of my brain when doing early work on opte. There's no reason that ownership shouldn't pass to the process method. A big benefit of this change is making it much less likely for leaking metadata between `process()` calls in a test (by forgetting to call `ActionMeta::clear()`.
You might wonder why ActionMeta is passed as argument at all; why not just conjure it inside `process()`? Well, it might be useful at some point to seed the `ActionMeta` with some values before calling into the port instance. If that turns out not to be true, then allocating it inside `process()` makes a lot more sense.

Pass ownership of ActionMeta

---

oxide-vpc/tests/common/mod.rs
oxide-vpc/tests/firewall_tests.rs
oxide-vpc/tests/integration_tests.rs

This makes it easier to assert drop results.
The other change I made was to change the `guest_to_guest_no_route()` test to verify the default outbound router rule, rather than using an explicit rule to drop all packets.

Add assert_drop macro

---

opte/src/engine/arp.rs
opte/src/engine/dhcpv6/protocol.rs
opte/src/engine/ether.rs
opte/src/engine/ip6.rs
opte/src/engine/packet.rs
oxide-vpc/tests/firewall_tests.rs
oxide-vpc/tests/integration_tests.rs
xde/src/mac.rs
xde/src/xde.rs

My initial thought back in August was to change the `Packet::wrap()` functions to return a `Result`; and if the length of the packet is zero bytes, to return an error. However, after spending more time with this, there's no real issue with wrapping a zero-byte packet. In fact, it simplifies the code to allow it. Instead, you deal with this scenario when attempting to parse the packet; returning an error indicating that the end of the packet has been reached unexpectedly.
While working on this I found that `Packet<Uninitialized>` and `PacketWriter` weren't really providing much use. Their original intent was to allocate a new mblk and write the packet from start to finish, converting it to `Packet<Initialized>` in which state you could no longer open a `PacketWriter` on it. But the primary …

Do not panic on zero-byte packet (#197)

---

opteadm/Cargo.lock
opteadm/Cargo.toml
opteadm/src/main.rs

Ran opteadm without pfexec and noticed it just panics for for `list-ports`. Looks like that was the only command using `unwrap()` instead of `unwrap_or_die()`. Just added anyhow which lets us throw in `?` instead everywhere.

opteadm: use anyhow instead of unwrapping.

---

.github/buildomat/jobs/opte-api.sh
.github/buildomat/jobs/opte-ioctl.sh
.github/buildomat/jobs/opte.sh
.github/buildomat/jobs/opteadm.sh
.github/buildomat/jobs/oxide-vpc.sh
.github/buildomat/jobs/xde.sh
illumos-sys-hdrs/src/lib.rs
opte-ioctl/Cargo.lock
opte-ioctl/Cargo.toml
opte/Cargo.lock
opte/Cargo.toml
opte/build.rs
opte/src/engine/flow_table.rs
opte/src/engine/layer.rs
opte/src/engine/mod.rs
opte/src/engine/packet.rs
opte/src/engine/rule.rs
opte/src/lib.rs
opteadm/Cargo.lock
opteadm/src/main.rs
oxide-vpc/Cargo.lock
oxide-vpc/Cargo.toml
oxide-vpc/tests/integration_tests.rs
rust-toolchain.toml
xde/Cargo.lock
xde/rust-toolchain.toml

With `asm_sym` stabilized, everything but xde can be built with stable.

Update for stable toolchain

---

opte/src/engine/predicate.rs
oxide-vpc/src/api.rs
oxide-vpc/src/engine/firewall.rs

I know the external IP hack is on the way out but in the meantime you need to add a firewall rule to allow incoming ARP packets past the firewall layer.
It's currently possible to do this via adding an overly permissive rule:
```console
$ opteadm add-fw-rule -p vm_test0 --action allow --dir in --hosts any --ports any --priority 65534 --protocol any
$ opteadm dump-layer -p vm_test0 firewall
[...snip...]
Inbound Rules
----------------------------------------------------------------------
ID     PRI    HITS   PREDICATES                             ACTION            
0      65534  0      *                                      "Stateful Allow"
```
With this PR you can make that a bit more fine grained:
```console
$ opteadm add-fw-rule -p vm_test0 --action allow --dir in --hosts any --ports any …
```

Allow filtering ARP packets in fw rule.

---

opte-api/src/dhcpv6.rs
opte-api/src/dns.rs
opte-api/src/ip.rs
opte-api/src/lib.rs
opte/src/engine/dhcp.rs
opte/src/engine/dhcpv6/options.rs
opte/src/engine/dhcpv6/protocol.rs
opteadm/src/main.rs
oxide-vpc/src/api.rs
oxide-vpc/src/engine/gateway/dhcp.rs
oxide-vpc/src/engine/gateway/dhcpv6.rs
oxide-vpc/tests/common/mod.rs
oxide-vpc/tests/integration_tests.rs

- Adds a basic DNS `DomainName` type, with minimal validation.
- Adds method to convert a list of `DomainName` to DHCPv6 option, and test for it.
- Add a `DomainSearchOpt` option to DHCP for encoding a list of domain names, and a test.
- Fixes bug in encoding of DHCPv6 `Option::DomainList`, trying to copy to wrong destination slice.
- Adds optional list of domain names to `VpcCfg`.
- Adds optional list of domain names to both DHCP and DHCPv6 actions, populated from the `VpcCfg`.
- Adds integration test for DHCPv6 Domain Search List, ensuring we get back in our reply the actual list the configuration describes.

Supply DNS domain search list option via `VpcCfg`

---

opte/Cargo.lock
opte/Cargo.toml
opte/src/engine/packet.rs

We previously used a statically-sized `heapless::Vec` inside the `Packet` type. That was used to represent the segments of a larger `mblk_t`, those linked by the `b_cont` field. This static array had enough space for 4 elements, and any attempt to push more segments panicked. We've now hit that.
This uses a straight-up Rust `Vec` instead of the `heapless` variant, to handle arbitrarily sized linked-lists of `mblk_t`s. This will address the immediate issue of panics. I've included a regression test for this.
However, we pay the cost of an allocation now. I've taken care that it's only one, by walking the `mblk_t` chain once to compute the size, allocating the `Vec`, and then walking the chain again to call `PacketSeg::wrap_mblk` on each. We may also pay an allocation cost when rewriting …

Handle longer chains of mblk segments

---

opte-api/Cargo.lock
opte-api/Cargo.toml
opte-api/src/ip.rs
opte-ioctl/Cargo.lock
opte/Cargo.lock
opteadm/Cargo.lock
oxide-vpc/Cargo.lock
xde/Cargo.lock

We already had some `From` impls to go between the standard rust IP types and our own. Added the other direction as well as conversions for the types from the `ipnetwork` crate which omicron makes use of.

Add some more conversions for IP types.

---

opte/src/engine/headers.rs
opte/src/engine/icmpv6.rs
opte/src/engine/mod.rs
opte/src/engine/packet.rs
opte/src/engine/predicate.rs
opteadm/src/main.rs
oxide-vpc/.gitignore
oxide-vpc/src/api.rs
oxide-vpc/src/engine/mod.rs
oxide-vpc/tests/common/mod.rs
oxide-vpc/tests/integration_tests.rs

Fixes:
1. We weren't setting the right hop limit (255) for the Neighbour Advertisement & Router Advertisement packets sent to the guest. 
2. Filled in some missing validity checks for Neighbour Solicitation & Router Solicitation packets received from the guest.
3. We were erroneously including the IPv6 base header size in the payload length when updating modified inner headers.
4. ICMPv6 checksums are calculated including an IP psuedo-header which meant the SNAT transformations would render them invalid. We now treat ICMPv6 as a psuedo ULP and handle checksum updates like TCP/UDP.
Misc:
1. Allow `opteadm` to create a port using IPv6.
2. Accept `icmp6` as a protocol filter when adding a firewall rule via `opteadm`.
Future:
It would be nice to be able to filter specific ICMP message types …

Update ICMPv6 checksum, set correct IPv6 payload len and misc

---

opte/src/engine/mod.rs
opte/src/engine/packet.rs
opte/src/engine/snat.rs
oxide-vpc/src/engine/mod.rs
oxide-vpc/tests/common/icmp.rs
oxide-vpc/tests/integration_tests.rs

This PR fixes the issue described in the following [comment](https://github.com/oxidecomputer/opte/blob/master/opte/src/engine/packet.rs#L1292-L1307). 
```
XXX This assumes that the headers all reside in the
first segment. For any typical implementation, this
should be true (it's better for performance, and
just makes the most sense). However, if that
invariant doesn't hold true, this method of erasing
the original header data is incomplete. It will
only partially erase the data, leading to confusion
downstream somewhere. The best solution is to check
for this during parsing. If the header straddles
segments, then just copy all header data into a new
segment, and replace the old header data with that
one segment. This means a hit on performance, but
it also means sanity for all downstream …
```

squash headers into single segment during parsing

---

opte/src/engine/port.rs
opte/src/engine/tcp_state.rs
oxide-vpc/tests/common/mod.rs
oxide-vpc/tests/firewall_tests.rs
oxide-vpc/tests/integration_tests.rs
xde/src/xde.rs

- Add error type for handling TCP flow errors
- Return new error variants rather than `String` from methods processing TCP flows.
- Handle TCP flow errors, now just unexpected segments, in the port processing code. This is done by returning a new `ProcessError` variant.
- Add `ProcessError::FlowTableFull`, which wraps attempts to add a new flow entry which fail because the table is full. This includes the table "kind", which for now is just a static string, and the current limit.
- Add an integration test verifying that TCP packets are dropped when the flow table is full.

Do not unwrap on flow table limits

---

oxide-vpc/tests/integration_tests.rs

Lag between when #347 was created vs merged means some tests need to be fixed.

Fix tests on main

---

opte/src/engine/packet.rs
oxide-vpc/tests/integration_tests.rs

When emitting headers, the structure of the message block for the packet being modified is somtimes altered. If the block holding the current headers is too small for the new headers, we shrink the old block by the size of the old headers, allocate a new block for the new headers and link the new block to the previous block through its continuation pointer. If the block being shurnk also contains ULP data this is fine. However, if it's purely a header block, then we wind up shrinking the old block to zero, and our new block has a zero sized continuation. This is not a generally expected situation and has caused NIC hardware to stop working. This commit prevents this from happening.
I placed a panic in `PacketSeg::link` that fires if we try to make a zero-sized continuation (only during …

prevent zero-sized continuation blocks

---

.github/buildomat/jobs/opte-api.sh
.github/buildomat/jobs/opte-ioctl.sh
.github/buildomat/jobs/opte.sh
.github/buildomat/jobs/opteadm.sh
.github/buildomat/jobs/oxide-vpc.sh
.github/buildomat/jobs/p5p.sh
.github/buildomat/jobs/test.sh
.github/buildomat/jobs/xde.sh
pkg/build.sh
pkg/opte.template.p5m

This change does a few things:
- removes the dependency the package has on itself
- changes the publisher name to **helios-dev** to match what we are presently using for Helios 2
- changes all the buildomat targets to Helios 2 targets

pkg: minor tweaks for Helios 2.0 packages

---

dtrace/opte-uft-hit.d
dtrace/opte-uft-invalidate.d
lib/opte/src/engine/port.rs
lib/opte/src/lib.rs

Adds a DTrace probe on UFT hit to allow us some observability, and adds a matching `.d` script using this probe. Additionally fixes up typos/old symbol names in `uft-hit-invaildate.d` (sic).
Closes #101.

Add UFT Hit probe for DTrace

---

lib/opte/src/ddi/kstat.rs
lib/opte/src/engine/dhcpv6/options.rs

`cargo test` was getting caught up on some doctests, correct and accidental. Code snippets in `ddi::kstat` were missing imports and had some obvious typos, while a packet diagram in `dhcp` was missing the `text` label.

Fix kstat/dhcp doctests and `cargo test`

---

lib/opte/src/engine/geneve.rs
lib/opte/src/engine/headers.rs
lib/opte/src/engine/packet.rs
lib/oxide-vpc/src/engine/overlay.rs
lib/oxide-vpc/tests/common/mod.rs
lib/oxide-vpc/tests/firewall_tests.rs
lib/oxide-vpc/tests/integration_tests.rs

This PR uses the presence of a min-sized Geneve TLV to detect packets on a given VNI which are originally external to the rack. To correctly filter such traffic at the firewall, the semantics of the `Address::Vni` host filter have changed to mean '*internal traffic* on this Vni'. Accordingly, I've added simple option parsing/emission.
This will require changes to Dendrite to correctly emit the new option on any SNAT transformations on ingress to the rack, as well as an OANA registration for option type 0.
Aims to fix #380 (in tandem with oxidecomputer/dendrite#606).

Filter and detect external traffic using Geneve option tags

---

lib/opte/src/engine/dhcp.rs
lib/opte/src/engine/dhcpv6/protocol.rs
lib/opte/src/engine/icmp.rs
lib/opte/src/engine/icmpv6.rs
lib/opte/src/engine/predicate.rs
lib/oxide-vpc/src/engine/gateway/icmpv6.rs
lib/oxide-vpc/tests/common/mod.rs
lib/oxide-vpc/tests/integration_tests.rs

Adds an additional gateway rule in each direction when v6-configured that will filter unexpected NDP traffic. I was unable to locally replicate the exact behaviour reported in omicron, but putting together some test cases similar enough to the original report confirmed the packets were uncaught (and should now be).
Also adds a `TypeMatch` so that we can express matches on collections with a little more ease. Predicates could also take another look, but that's out of scope for this bugfix PR.
Closes #356.

Filter all uncaught {In, Out} NDP traffic

---

bin/opteadm/src/bin/opteadm.rs
bin/opteadm/src/lib.rs
crates/opte-api/src/cmd.rs
crates/opte-api/src/lib.rs
lib/opte/src/engine/ioctl.rs
lib/opte/src/engine/port.rs
xde/src/xde.rs

- Add `OpteCmd::ClearLft` & `ClearLftReq` to ioctl API.
- Update xde to handle new req (^) and plumb down to existing `Layer::clear_flows` method in opte.
- Update `opteadm` with new `clear-lft` command.
Closes #397.

Expose API for clearing a specific layer's flow table entries.

---

.github/renovate.json

This is almost identical to the configuration in omicron today. We don't need to perform any post-upgrade commands, so we can remove the line of config that adds that functionality.
Closes #401.

Add base configuration for renovate.

---

lib/opte/src/engine/headers.rs
lib/opte/src/engine/icmp/v4.rs
lib/opte/src/engine/nat.rs
lib/opte/src/engine/snat.rs
lib/oxide-vpc/src/api.rs
lib/oxide-vpc/src/engine/nat.rs
lib/oxide-vpc/tests/common/icmp.rs
lib/oxide-vpc/tests/integration_tests.rs

This PR takes advantage of the extra plumbing added in #408 to add ICMP Echo ID/SNAT port substitution to ICMPv6, allowing `ping` to function for IPv6 hosts/VMs without ephemeral IPs. This follows on from how ICMP v4 and v6 are both now treated as full ULPs, and makes use of the newer `icmp_id` header transform.
Additionally, there's some amount of cleanup done here. Now that we can handle these protocols identically, OPTE folds `SNat` and `SNat6` into a single `SNat<T: ConcreteIpAddr>` -- this lets us remove a lot of duplicated code between V4 and V6 impls of e.g. `ActionDesc`.
Closes #411.

Enable ICMP Echo Request/Reply rewriting through IPv6 SNAT

---

lib/opte/src/engine/rule.rs
lib/opte/src/engine/snat.rs
lib/oxide-vpc/src/engine/nat.rs

This PR provides TCP/UDP/ICMP-Echo traffic on a SNAT with separate pools of available public ports for use, and moves some elements of `NatEntry` structs into a shared handle to simplify correctly returning ports to the intended pool.
Closes #412.

Implement Per-ULP SNAT allocation

---

dtrace/opte-flow-expire.d
dtrace/opte-uft-hit.d
dtrace/usdt-opte-flow-expire.d
lib/opte/src/ddi/time.rs
lib/opte/src/engine/flow_table.rs
lib/opte/src/engine/port.rs
lib/opte/src/lib.rs

Adds some extra probes to help us track down and verify #426, and also
slightly changes up `Moment::delta_as_millis()` to saturate if the order
if `now` and `earlier` are seemingly back to front (as is apparently
now standard behaviour in std).

Add `last_hit` to uft hit/expire probes, prevent `Moment` time delta wrapping

---

lib/opte/src/engine/port.rs
lib/oxide-vpc/tests/integration_tests.rs
xde/src/xde.rs

Closes #426. #427 had already patched over this behaviour by preventing wrap on timestamp comparison, but now we can be certain that this is the race window which was being hit.

Move `Moment::now()` into lock for UFT expiry

---

lib/opte/src/engine/flow_table.rs
lib/opte/src/engine/port.rs
lib/opte/src/engine/tcp.rs
lib/opte/src/engine/tcp_state.rs
lib/oxide-vpc/tests/common/mod.rs
lib/oxide-vpc/tests/integration_tests.rs

This PR introduces two key changes to how we handle TCP flows, and refactors to give us some more consistency between how they're handled by {in, out}bound packets when we {do, don't} have an existing UFT entry.
At present, TCP sessions which have been passive-closed by the guest are correctly moved to the CLOSED state and removed, while those which are active-closed become stuck in a TIME_WAIT state.
To remedy this, we add two fairly pessimistic cleanup timers: 120s for TIME-WAIT, and 2.5 hours for other states (the default 2 hour SO_KEEPALIVE time with a fudge factor). The CLOSED -> ESTABLISHED shortcut should allow an entry to be readded with shorter timers, however we might in future store more detailed flow state which would be lost with a shorter timeout.
Existing TCP flows will no …

TCP flow state refactor and fixes

---

Cargo.lock
Cargo.toml
bin/opteadm/Cargo.toml
bin/opteadm/src/bin/opteadm.rs
lib/opte/Cargo.toml
lib/opte/src/engine/print.rs
lib/oxide-vpc/Cargo.toml
lib/oxide-vpc/src/engine/print.rs
lib/oxide-vpc/tests/common/mod.rs
lib/oxide-vpc/tests/common/port_state.rs
lib/oxide-vpc/tests/integration_tests.rs

This PR changes the formatting on opteadm to be constructed using TabWriter, which should provide a small improvement over the (many) hand-coded padding lengths in today's output strings.
For additional tweaks I've also added the current port name to the output of `opteadm dump-layer`, which should make it somewhat easier to track down the right layers when looking at integration test output on omicron. Multiple external IPs in `list-ports` are now also split over newlines, matching the style of multi-predicate layer rules.

Use TabWriter for `opteadm` output

---

.cargo/config.toml
.github/buildomat/jobs/opte-api.sh
.github/buildomat/jobs/opte-ioctl.sh
.github/buildomat/jobs/opte.sh
.github/buildomat/jobs/opteadm.sh
.github/buildomat/jobs/oxide-vpc.sh
.github/buildomat/jobs/p5p.sh
.github/buildomat/jobs/xde.sh
Cargo.lock
Cargo.toml
README.adoc
pkg/build.sh
pkg/opte.template.p5m
xde/build-debug.sh
xde/build.sh
xde/rust-toolchain.toml
xde/x86_64-unknown-unknown.json
xtask/Cargo.toml
xtask/src/main.rs

This PR adds some `cargo xtask`s to build and install XDE and opteadm on a given host -- `cargo xtask {build, install, package}`. These include flags for `pkg`-based installation as well as a brute-force method which simply copies our artifacts into the right place.
I've also bumped the nightly toolchain used by XDE since it's been some time since we've done so, and added `cargo xtask fmt` to automatically format using the correct nightly toolchain.
Closes #413 and closes #366.

Add Xtask for XDE build/install/package operations

---

lib/opte/src/engine/geneve.rs
lib/opte/src/engine/packet.rs
lib/opte/src/engine/port.rs
lib/oxide-vpc/tests/common/mod.rs
lib/oxide-vpc/tests/integration_tests.rs
rust-toolchain.toml

The `encap` method has, for its lifetime, been adding the length of a UDP header as well as `GeneveHdr::BASE_SIZE` when computing the length of the Geneve packet metadata for encapsulating test packets. However, `GeneveHdr` already includes UDP and its fields, so we were requesting an extra 8 bytes without initialising them. This PR corrects that length computation.
Fixes #454.

Fix Geneve size in `integration_tests::common::encap`

---

lib/opte/src/engine/port.rs

Outbound TCP packets which transitioned the state machine to `Closed` were
double-removing the TCP flow entries allocated to them. This is not bad on its
own due to the table lock. However, the inbound UFID was being always being
reported as `None` in this case. Ultimately, we need both UFIDs to remove
both UFT entries.
The inbound UFID used to invalidate both UFT entries was being computed from a
second remove in e.g. `process_out_tcp_existing`. Naturally this returned `None`,
as the TCP flow entry has already been removed. This resulted in the inbound UFID
always being `None` -- a later call to `update_tcp_entry` thus removes only the
outbound UFT entry and leaves a dangling inbound UFT entry.
This dangling entry prevents new inbound TCP flows on the same 5-tuple for a time
of 1 minute …

Correctly preserve inbound UFID on outbound TCP close

---

xtask/src/main.rs

Using `cargo xtask install` without `--from-package` was relying on leftover state to actually work and would otherwise fail on clean system.

Fix xtask non-package install for fresh systems.

---

lib/opte/src/engine/port.rs
lib/oxide-vpc/tests/integration_tests.rs

Removing an inbound UFT entry in response to a TCP closure requires
that we remove it using its pre-transform flow ID, rather than
`pkt.flow()`. This is what `TcpFlowEntryState.inbound_ufid` was intended
to capture. To-date, we have been filling in this optional inbound flow
ID on a TCP flow entry using its post-transformation metadata -- either
`pkt.flow()` or `InnerFlowId::from(pmeta)`. This results in a mismatch:
* The UFT is keyed on pre-transform flow ID, e.g., ephemeral IP + remote
IP.
* The TCP flow table is always keyed on, e.g., private IP + remote IP.
So nothing is removed from the inbound UFT table when a TCP flow triggers
early UFT invalidation.
We now correctly use the initial `flow_before` on all inbound TCP flows.
Additionally, we create a new TCP flow entry and allow …

Fix opte#469 for VPC-external flows

---

Cargo.lock
bin/opteadm/src/bin/opteadm.rs
bin/opteadm/src/lib.rs
crates/opte-api/src/cmd.rs
crates/opte-api/src/lib.rs
lib/opte-ioctl/src/lib.rs
lib/oxide-vpc/src/api.rs
lib/oxide-vpc/src/engine/overlay.rs
lib/oxide-vpc/src/engine/print.rs
xde/src/xde.rs

We're adding rpws to Omicron so we can keep the v2p mappings consistent across sled reboots and other unfortunate-but-necessary events. Currently, sled-agent nor omicron has the ability to determine what mappings already exists, so it's difficult to reconcile or detect conflicting mappings.
Related
---
Closes https://github.com/oxidecomputer/opte/issues/332

add ability for omicron to observe v2p mappings

---

lib/opte-ioctl/src/lib.rs

Something in Rust 1.78.0 changed (not sure what, maybe the upgrade to LLVM 18?) which reliably triggers this assert:
https://github.com/oxidecomputer/opte/blob/7ee353a470ea59529ee1b34729681da887aa88ce/lib/opte-ioctl/src/lib.rs#L293-L294
while sled-agent is coming up in a deployment. ([buildomat deploy job logs](https://buildomat.eng.oxide.computer/wg/0/details/01HXDKSYDNP1YXFRVFP2ZRSNDA/9lEm5MXpBdPO8UQZHmGRfgQPkGAXQzPGRkrXYSTgqWvK4EJO/01HXDKT6YYQTE3PX5X88ZMPGW0))
Correctly using a mutable reference for `rioctl` in the `libc::ioctl` call fixes this issue. It's unclear to me whether this is a case of Rust/LLVM deciding it can optimize out the assertion predicate because `rioctl` wasn't marked as mutating between declaration and then.

fix mutability of ioctl argument

---

bin/opteadm/src/bin/opteadm.rs
bin/opteadm/src/lib.rs
crates/opte-api/src/cmd.rs
crates/opte-api/src/lib.rs
lib/opte-ioctl/src/lib.rs
xde-tests/src/lib.rs
xde/src/xde.rs
xtask/src/main.rs

This PR moves the underlay teardown logic from xde_detach into a new ioctl (and opteadm command) to unset the XDE underlay. Detach will now fail so long as the underlay is set -- this successfully prevents `modunload` from knocking us down after this state has been set.
The semantics are more or less what you'd expect:
* Clearing the underlay will fail if there exists a port.
* Clearing the underlay will fail if there is no underlay.
* Driver detach now requires that you `opteadm clear-xde-underlay`.

Prevent modunload once underlay has been set

---

crates/illumos-sys-hdrs/src/kernel.rs
lib/opte/src/engine/packet.rs
xde/src/mac.rs
xde/src/xde.rs

This PR adds a `PacketChain` type which takes ownership of an `mblk_t` and then serves out owned `Packet<Initialized>` entitites for the rest of the stack to use.
This doesn't fundamentally change how we're structuring Packets internally, which still compute/allocate a Vec of `b_cont` entries. At the same time, we're still serving packets to our chosen destination MAC clients one by one. We will probably want to do some work here to better support reconstructing chains to hand off, where we can.
Closes #237.

Handle `mblk_t` packet chains

---

lib/opte/src/d_error.rs
lib/opte/src/engine/packet.rs
lib/opte/src/engine/rule.rs
xde/src/lib.rs
xde/src/route.rs
xde/src/xde.rs

This PR inserts a caching layer in front of `next_hop` to store routes for a given `(IpAddr6, L4Hash)` for around 100ms, and reorganises routing-related code into `xde::route`. This is a necessary step as today we spend around 21% of `xde_mc_tx` in route lookup on a per-outbound-packet basis. As a consequence, we need install a new `Periodic` to flush expired entries every 1s, as otherwise we can have a large amountof detritus pileup from different L4Hash values.
Currently this is implemented as a per-port cache rather than shared across the driver -- I've done this because it will give us better sharding of concurrent readers/writers at higher port/guest counts. The PR as-is pulls us up from  ~1.74Gbps to 2Gbps on a single link between sn9/14.
I'm seeing similar gain on the …

Cache routes received from `next_hop`

---

lib/opte/src/ddi/sync.rs
xde/src/xde.rs

As part of #485, we need to *inspect* the contents of the shared `XdeState` before taking ownership and dropping its contents. However, I had created a scenario where:
- The lock is acquired, based on a reference derived from the dev info ptr (`dip`),
- Ownership of the contents of `dip` is taken using `Box::new_raw`,
- These contents (`XdeState`) are freed,
- The `MutexGuard` pointing into the `XdeState` is dropped, and attempts to unlock a freed mutex.
This PR scopes the `&XdeState` and the derived `MutexGuard` in an inner block, correcting this drop order issue by forcing the free to happen at the end of a lexical scope.
Fixes #543.

Correctly scope lock use in `xde_detach`

---

bench/src/packet.rs
bin/opteadm/src/bin/opteadm.rs
bin/opteadm/src/lib.rs
crates/opte-api/src/cmd.rs
crates/opte-api/src/ip.rs
crates/opte-api/src/lib.rs
lib/opte-ioctl/src/lib.rs
lib/opte-test-utils/src/lib.rs
lib/opte/src/engine/port.rs
lib/oxide-vpc/src/api.rs
lib/oxide-vpc/src/engine/gateway/mod.rs
lib/oxide-vpc/src/engine/gateway/transit.rs
lib/oxide-vpc/src/engine/router.rs
lib/oxide-vpc/tests/integration_tests.rs
xde-tests/src/lib.rs
xde/src/xde.rs

This PR introduces various features needed in OPTE side for VPC subnet routing:
* Add ioctl for deletion of router rules.
* Support for the 'system' vs 'custom' router distinction, and prioritisation of 'custom' rules of equal prefix length.
* Allow IP spoof-detection to be disabled (and re-enabled) on a per-CIDR basis. This is necassary to enable rules such as `192.168.0.0/16 -> ip(instance_abc)` for software routing or enabling VPN endpoints.
I'm leaving this in draft while the omicron-side pieces are in development.

VPC Subnet Routing

---

bench/Gimlet.adoc
bench/benches/xde.rs
dtrace/opte-count-cycles.d
xde-tests/src/lib.rs

This is a necessity for testing on newly-built bench gimlet images -- even if `sparse` is included, I've been unable to get their zones to come up due to supposed publisher/incorporation lookup issues.
On the other hand, a helios experiment-image built with extra packages like iperf will place all those into the omicron1 baseline where we need them, so this is the simplest fix to run both halves on sn9/14.

Expose choice of zone brand on kbench remote/server

---

.github/buildomat/jobs/opteadm.sh
.github/buildomat/jobs/xde.sh
Cargo.lock
Cargo.toml
bench/src/packet.rs
bin/opteadm/src/bin/opteadm.rs
lib/opte-test-utils/src/lib.rs
lib/oxide-vpc/Cargo.toml
lib/oxide-vpc/src/api.rs
lib/oxide-vpc/src/engine/nat.rs
lib/oxide-vpc/src/engine/overlay.rs
lib/oxide-vpc/src/engine/router.rs
lib/oxide-vpc/tests/firewall_tests.rs
lib/oxide-vpc/tests/integration_tests.rs

The Omicron internet gateway model associates IP pools, and subsequently addresses from those IP pools, with internet gateways. When packets are directed at an internet gateway through a VPC route, they should take on a source address from the IP pool that is tied to the target internet gateway. This trivially happens when there is only one internet gateway and an instance only has an address from one IP pool. But when there are multiple IP pools in play, particularly with floating IPs from different pools, a decision needs to be made about which one to use. That question is answered by the IP-pool/internet-gateway association in combination with VPC routes that direct packets at a particular internet gateway.
This PR provides OPTE machinery for realizing Omicron internet gateway model. …

Support for omicron internet gateway model

---

lib/opte-ioctl/src/lib.rs
lib/opte/src/engine/port.rs

Now that the fastpath temporarily drops (and reacquires) the port lock when TCP state needs to be invalidated, we opened ourselves up to the possibility that another packet could have removed this state ahead of us. Equally, a packet could insert new TCP state which we might accidentally remove.
This PR removes the unwrap on removal to account for the race, and only removes TCP flows if they are pointer-equal.
Closes #618, closes #624.

Don't unwrap when removing invalid TCP state from fastpath.

---

Cargo.lock
bench/benches/xde.rs
bin/opteadm/src/bin/opteadm.rs
xde-tests/Cargo.toml
xde-tests/src/lib.rs
xde/src/dev_map.rs
xde/src/lib.rs
xde/src/xde.rs

This PR moves all lookup of ports by data- and control-plane operations to make use of `BTreeMap`s and prevent linear scans from being used in any case. `cargo kbench` now supports the `-P` flag to spin up a number of ports with random MAC/VNI combinations.
On `glasgow`, using `./kbench remote -b omicron1 -u cxgbe0 cxgbe1 172.20.2.114 -p -P $N_PORTS` + `iperf -c 10.0.0.1 -R`, the measured throughput remains in the 2.85–3.0Gbps range regardless of choice of `-P` (up to 4096). At 16384 ports we could no longer consistently hit 3Gbps, but we hadn't dipped too badly (2.8–2.9Gbps). I haven't measured control-plane-op/remove times, but I would expect that they enjoy similar speedup at large port counts. E.g., firewall/router/IP state updates all require a name lookup to apply. Addition of ports …

Use `BTreeMap`s to accelerate port lookup by name & VNI/MAC address

---

Cargo.lock
Cargo.toml

Also update libnet to explicitly specify `main`, in order to ensure that two
copies of the crate aren't floating around in other dependency graphs.

update oxnet to 0.1.0 from crates.io

---

lib/opte/src/ddi/sync.rs
lib/opte/src/engine/port.rs
lib/opte/src/engine/snat.rs
lib/oxide-vpc/src/engine/overlay.rs
xde/src/xde.rs

Pulled out of #636. We were creating some `Spin` locks which, misconfigured, would end up falling back to adaptive behaviour as part of LFT creation. Moreover, they would hit a debug assert and panic on test bits. (!!!)
Given that we have no means of specifying priority in `mutex_init`, we now make sure that all created `KMutex`es are correct by removing the illusion of free choice.

Only use `KMutexType::Driver` in `mutex_init`

---

.github/buildomat/common.sh
.github/buildomat/jobs/bench.sh
.github/buildomat/jobs/opte-api.sh
.github/buildomat/jobs/opte-ioctl.sh
.github/buildomat/jobs/opte.sh
.github/buildomat/jobs/opteadm.sh
.github/buildomat/jobs/oxide-vpc.sh
.github/buildomat/jobs/p5p.sh
.github/buildomat/jobs/test.sh
.github/buildomat/jobs/xde.sh

CI on recent PRs is breaking, due to rustup 1.28.0+ no longer autoinstalling the correct rust toolchain version. This hurts us immediately since we have *two* toolchains (pinned nightly and stable), and deliberately specified the nightly for some tooling.
This PR changes this over to use buildomat's auto-installation for the stable variant, and the new toolchain show -> install pattern for nightly. This also lets us place `$NIGHTLY` into most of our `cargo fmt` invocations, which should reduce the busywork in future compiler bumps for XDE.

Rework rust toolchain installation

---

.cargo/config.toml
Cargo.toml
pkg/build.sh
xtask/src/main.rs

Before:
```bash
kyle@farme:~/gits/opte$ time cargo xtask install
...
Compiling xtask v0.1.0 (/develop/gits/opte/xtask)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 15.26s
Running `target/debug/xtask install`
Building opteadm (release).
...
Compiling oxide-vpc v0.1.0 (/develop/gits/opte/lib/oxide-vpc)
Compiling opte-ioctl v0.1.0 (/develop/gits/opte/lib/opte-ioctl)
Finished `release` profile [optimized + debuginfo] target(s) in 54.47s
Building xde (release).
Compiling xde v0.1.0 (/develop/gits/opte/xde)
Finished `release` profile [optimized + debuginfo] target(s) in 56.70s
Linking xde kmod...
Building xde dev link helper (release).
Compiling compiler_builtins v0.1.146
Compiling core v0.0.0 (/home/kyle/.rustup/toolchains/nightly-2025-02-20-x86_64-unknown-illumos/lib/rustlib/s …
```

Only compile XDE/ubench with LTO enabled

---

lib/opte/src/ddi/mblk.rs
lib/oxide-vpc/src/engine/overlay.rs
xde/src/xde.rs

First, we missed one branch in the overlay action for setting the `mtu_unrestricted` property on VPC-local packets. This ended up getting missed because the bench/xde-test runner set up the routing table differently to omicron.
Second, when we open up some limited ICMP families for Nexus (intending to support PMTUD), the illumos TCP stack will have its own (and better!) idea about what MSS is actually assigned to a flow. We now reuse this MSS when not explicitly boosting a flow into jumbo frame territory.
Closes #747.
Closes #748.

Various MTU fixes.

---

Cargo.toml

Shaves a few MB off the binary size of XDE, but does not seem to improve performance any.
So far as I can tell on my workstation, this has a minimal impact on build times. Double checking that this holds true from CI.

Build release XDE with `codegen-units = 1`

---

.github/buildomat/jobs/bench.sh
.github/buildomat/jobs/test.sh
bench/benches/xde.rs
xde-tests/src/lib.rs
xde-tests/tests/loopback.rs

Very quick PR to enable use of the `omicron1` brand in the `kbench local` benchmark, and the xde simnet connectivity test. This shaves a good 6 min off `xde-test` and `bench` in CI -- since sparse zones take so long to setup that it's worth spending ~1min to build the baseline for omicron1 zones.
Basically, this zone type requires that we put a VNIC ontop of each simnet endpoint and then use *that* as the underlay. This is also, as it turns out, a requirement to use packet siphons in these test cases.

Use `omicron1` brand in CI

---

lib/opte/src/engine/port/meta.rs
lib/oxide-vpc/src/engine/gateway/mod.rs
lib/oxide-vpc/src/engine/nat.rs
lib/oxide-vpc/src/engine/overlay.rs
lib/oxide-vpc/src/engine/router.rs

Mooves `ActionMeta` from a `String`->`String` map to something capable of holding `&'static str`s as both keys and values. This only really affects slowpath traffic, but this leads to fewer allocations when traversing that path.
Split out of #805, where this wasn't a necessary part of the fix.

`Cow`-ify `ActionMeta`

---

xde/src/postbox.rs

We keep track of `MsgBlkChain`s in a `BTreeMap` today. Sadly this isn't a type which we can preallocate a desired capacity in and store per-CPU. As a result, for flamegraphs in the Rx pathway we can see a moderately chunky call into `kmem_alloc` within `Postbox::post` for chains which have one recipient.
This PR special-cases the single-recipient case so that we hold onto one chain and key on the heap until needed.

Don't allocate in `BTreeMap` when only one postbox is needed
